import "dotenv/config";
import { Categories, Products, sequelize } from "./models";

const categories = [
    { type: "remera", subtype: "manga corta" },
    { type: "remera", subtype: "manga larga" },
    { type: "calzado", subtype: "zapatillas" },
    { type: "calzado", subtype: "botas" },
    { type: "pantalon", subtype: "jean" },
    { type: "pantalon", subtype: "jogger" }
];

async function setupDatabase(): Promise<void> {
    console.log("Conectando con CockroachDB...");
    await sequelize.authenticate();
    console.log("Conexión establecida. Preparando catálogo...");
    await sequelize.query(`
        CREATE TABLE IF NOT EXISTS categories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type STRING(255) NOT NULL,
            subtype STRING(255)
        )
    `);
    await sequelize.query(`
        CREATE TABLE IF NOT EXISTS products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name STRING(255) NOT NULL,
            price INT NOT NULL,
            category_id BIGINT NOT NULL REFERENCES categories(id),
            type STRING(100),
            talles STRING(255),
            description STRING(255),
            stock INT,
            sales_count INT DEFAULT 0,
            imagen1 STRING(255),
            imagen2 STRING(255),
            imagen3 STRING(255)
        )
    `);
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS type STRING(100)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS sales_count INT DEFAULT 0");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS slug STRING(255)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS sku STRING(80)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS brand STRING(120)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS gender STRING(40)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS color STRING(80)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS material STRING(120)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS compare_price INT");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS is_featured BOOL DEFAULT false");
    await sequelize.query(`
        CREATE TABLE IF NOT EXISTS product_images (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            url STRING(500) NOT NULL,
            alt_text STRING(255) NOT NULL,
            sort_order INT NOT NULL DEFAULT 0,
            is_primary BOOL NOT NULL DEFAULT false,
            source_type STRING(30) NOT NULL DEFAULT 'local'
        )
    `);
    await sequelize.query(`
        CREATE TABLE IF NOT EXISTS product_variants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            size STRING(30) NOT NULL,
            color STRING(80),
            stock INT NOT NULL DEFAULT 0,
            UNIQUE (product_id, size, color)
        )
    `);

    if (await Categories.count() === 0) {
        await Categories.bulkCreate(categories);
    }

    const categoryRows = await Categories.findAll({ order: [["id", "ASC"]] });
    const categoryByType = new Map(categoryRows.map((category) => [category.type, category.id]));
    const products = [
        {
            name: "Buzo oversize Essential",
            type: "abrigo",
            category_id: categoryByType.get("pantalon")!,
            price: 18900,
            description: "Buzo oversize de frisa, calce relajado y estilo urbano.",
            talles: "S,M,L,XL",
            stock: 12,
            imagen1: "buzo2.png"
        },
        {
            name: "Remera Street Club",
            type: "remera",
            category_id: categoryByType.get("remera")!,
            price: 9900,
            description: "Remera de algodon premium con estampa urbana.",
            talles: "S,M,L,XL",
            stock: 18,
            imagen1: "remera1.png"
        },
        {
            name: "Pantalon cargo Utility",
            type: "pantalon",
            category_id: categoryByType.get("pantalon")!,
            price: 24900,
            description: "Pantalon cargo de corte recto con bolsillos laterales.",
            talles: "28,30,32,34,36",
            stock: 9,
            imagen1: "model1.jpg"
        },
        {
            name: "Falda urbana Denim",
            type: "pantalon",
            category_id: categoryByType.get("pantalon")!,
            price: 17900,
            description: "Falda urbana de denim para combinar con tus basicos.",
            talles: "S,M,L",
            stock: 7,
            imagen1: "falda.png"
        },
        {
            name: "Vestido Daily Black",
            type: "vestido",
            category_id: categoryByType.get("remera")!,
            price: 21900,
            description: "Vestido negro versatil para un look urbano diario.",
            talles: "S,M,L",
            stock: 6,
            imagen1: "vestido1.png"
        },
        {
            name: "Campera Urban Light",
            type: "abrigo",
            category_id: categoryByType.get("pantalon")!,
            price: 32900,
            description: "Campera liviana de inspiracion streetwear.",
            talles: "S,M,L,XL",
            stock: 5,
            imagen1: "bebestreet.png"
        },
        {
            name: "Buzo Core Fleece",
            type: "abrigo",
            category_id: categoryByType.get("pantalon")!,
            price: 22400,
            compare_price: 26900,
            description: "Buzo de frisa pesada con capucha y calce amplio.",
            talles: "S,M,L,XL",
            stock: 14,
            sales_count: 39,
            is_featured: true,
            brand: "C Zone",
            gender: "unisex",
            color: "gris grafito",
            material: "algodon y poliester",
            slug: "buzo-core-fleece",
            sku: "CZ-BUZ-001",
            imagen1: "buzo1.png"
        },
        {
            name: "Remera Heavy Basic",
            type: "remera",
            category_id: categoryByType.get("remera")!,
            price: 11900,
            description: "Remera de jersey pesado, hombro caido y cuello reforzado.",
            talles: "S,M,L,XL",
            stock: 24,
            sales_count: 52,
            is_featured: true,
            brand: "C Zone",
            gender: "unisex",
            color: "blanco",
            material: "algodon 100%",
            slug: "remera-heavy-basic",
            sku: "CZ-REM-001",
            imagen1: "remera1.png"
        },
        {
            name: "Remera Boxy Acid",
            type: "remera",
            category_id: categoryByType.get("remera")!,
            price: 13500,
            compare_price: 15900,
            description: "Remera boxy de inspiracion street con lavado desgastado.",
            talles: "S,M,L",
            stock: 11,
            sales_count: 31,
            brand: "C Zone",
            gender: "unisex",
            color: "negro lavado",
            material: "algodon",
            slug: "remera-boxy-acid",
            sku: "CZ-REM-002",
            imagen1: "model1.jpg"
        },
        {
            name: "Jogger Relax Essential",
            type: "pantalon",
            category_id: categoryByType.get("pantalon")!,
            price: 19900,
            description: "Jogger de calce relajado con cintura elastizada.",
            talles: "S,M,L,XL",
            stock: 16,
            sales_count: 46,
            is_featured: true,
            brand: "C Zone",
            gender: "unisex",
            color: "negro",
            material: "frisa de algodon",
            slug: "jogger-relax-essential",
            sku: "CZ-JOG-001",
            imagen1: "buzo2.png"
        },
        {
            name: "Jean Straight Raw",
            type: "pantalon",
            category_id: categoryByType.get("pantalon")!,
            price: 28900,
            description: "Jean recto de tiro medio con lavado azul profundo.",
            talles: "28,30,32,34,36",
            stock: 10,
            sales_count: 37,
            brand: "C Zone",
            gender: "unisex",
            color: "azul denim",
            material: "denim",
            slug: "jean-straight-raw",
            sku: "CZ-JEA-001",
            imagen1: "falda.png"
        },
        {
            name: "Campera Wind Shell",
            type: "abrigo",
            category_id: categoryByType.get("pantalon")!,
            price: 38900,
            description: "Campera liviana con cierre frontal y silueta tecnica.",
            talles: "S,M,L,XL",
            stock: 8,
            sales_count: 29,
            is_featured: true,
            brand: "C Zone",
            gender: "unisex",
            color: "verde oliva",
            material: "nylon",
            slug: "campera-wind-shell",
            sku: "CZ-CAM-001",
            imagen1: "bebestreet.png"
        },
        {
            name: "Vestido Rib Daily",
            type: "vestido",
            category_id: categoryByType.get("remera")!,
            price: 22900,
            description: "Vestido midi de morley con silueta limpia y comoda.",
            talles: "S,M,L",
            stock: 9,
            sales_count: 24,
            brand: "C Zone",
            gender: "mujer",
            color: "negro",
            material: "algodon y elastano",
            slug: "vestido-rib-daily",
            sku: "CZ-VES-001",
            imagen1: "vestido1.png"
        },
        {
            name: "Set Top y Short Move",
            type: "conjunto",
            category_id: categoryByType.get("remera")!,
            price: 25900,
            description: "Conjunto versatil de top y short para moverte comoda.",
            talles: "S,M,L",
            stock: 7,
            sales_count: 18,
            brand: "C Zone",
            gender: "mujer",
            color: "negro",
            material: "algodon y elastano",
            slug: "set-top-short-move",
            sku: "CZ-SET-001",
            imagen1: "falda.png"
        }
    ];

    for (const product of products) {
        const existingProduct = await Products.findOne({ where: { name: product.name } });
        if (!existingProduct) {
            await Products.create(product);
        }
    }

    console.log(`Productos base procesados: ${products.length}`);

    const allProducts = await Products.findAll();
    for (const product of allProducts) {
        const image = product.imagen1;
        if (image) {
            await sequelize.query(`
                INSERT INTO product_images (product_id, url, alt_text, sort_order, is_primary, source_type)
                SELECT :productId, :url, :altText, 0, true, 'local'
                WHERE NOT EXISTS (SELECT 1 FROM product_images WHERE product_id = :productId AND url = :url)
            `, { replacements: { productId: product.id, url: `/img/${image}`, altText: `${product.name} - imagen principal` } });
        }
        const sizes = (product.talles || "unico").split(",").map((size) => size.trim());
        for (const size of sizes) {
            await sequelize.query(`
                INSERT INTO product_variants (product_id, size, color, stock)
                SELECT :productId, :size, :color, :stock
                WHERE NOT EXISTS (SELECT 1 FROM product_variants WHERE product_id = :productId AND size = :size AND COALESCE(color, '') = COALESCE(:color, ''))
            `, { replacements: { productId: product.id, size, color: product.color || null, stock: Math.max(0, Math.floor((product.stock || 0) / sizes.length)) } });
        }
    }

    console.log(`Imágenes y variantes procesadas para ${allProducts.length} productos`);

    await Products.update({ sales_count: 84 }, { where: { name: "Buzo oversize Essential" } });
    await Products.update({ sales_count: 71 }, { where: { name: "Remera Street Club" } });
    await Products.update({ sales_count: 63 }, { where: { name: "Zapatillas deportivas" } });
    await Products.update({ sales_count: 55 }, { where: { name: "Pantalon de jean" } });
    await Products.update({ sales_count: 48 }, { where: { name: "Pantalon cargo Utility" } });
    await Products.update({ sales_count: 41 }, { where: { name: "Campera Urban Light" } });

    console.log(`Base lista: ${await Categories.count()} categorias, ${await Products.count()} productos.`);
}

setupDatabase()
    .catch((error) => {
        console.error("No se pudo preparar la base de datos:", error.message);
        process.exitCode = 1;
    })
    .finally(() => sequelize.close());