import "dotenv/config";
import { Categories, Products, sequelize } from "./models";

const categories = [
    { type: "remera", subtype: "manga corta" },
    { type: "remera", subtype: "manga larga" },
    { type: "calzado", subtype: "zapatillas" },
    { type: "calzado", subtype: "botas" },
    { type: "pantalon", subtype: "jean" },
    { type: "pantalon", subtype: "jogger" }
];

async function setupDatabase(): Promise<void> {
    await sequelize.authenticate();
    await sequelize.query(`
        CREATE TABLE IF NOT EXISTS categories (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type STRING(255) NOT NULL,
            subtype STRING(255)
        )
    `);
    await sequelize.query(`
        CREATE TABLE IF NOT EXISTS products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name STRING(255) NOT NULL,
            price INT NOT NULL,
            category_id BIGINT NOT NULL REFERENCES categories(id),
            type STRING(100),
            talles STRING(255),
            description STRING(255),
            stock INT,
            sales_count INT DEFAULT 0,
            imagen1 STRING(255),
            imagen2 STRING(255),
            imagen3 STRING(255)
        )
    `);
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS type STRING(100)");
    await sequelize.query("ALTER TABLE products ADD COLUMN IF NOT EXISTS sales_count INT DEFAULT 0");

    if (await Categories.count() === 0) {
        await Categories.bulkCreate(categories);
    }

    const categoryRows = await Categories.findAll({ order: [["id", "ASC"]] });
    const categoryByType = new Map(categoryRows.map((category) => [category.type, category.id]));
    const products = [
        {
            name: "Buzo oversize Essential",
            type: "abrigo",
            category_id: categoryByType.get("pantalon")!,
            price: 18900,
            description: "Buzo oversize de frisa, calce relajado y estilo urbano.",
            talles: "S,M,L,XL",
            stock: 12,
            imagen1: "buzo2.png"
        },
        {
            name: "Remera Street Club",
            type: "remera",
            category_id: categoryByType.get("remera")!,
            price: 9900,
            description: "Remera de algodon premium con estampa urbana.",
            talles: "S,M,L,XL",
            stock: 18,
            imagen1: "remera1.png"
        },
        {
            name: "Pantalon cargo Utility",
            type: "pantalon",
            category_id: categoryByType.get("pantalon")!,
            price: 24900,
            description: "Pantalon cargo de corte recto con bolsillos laterales.",
            talles: "28,30,32,34,36",
            stock: 9,
            imagen1: "model1.jpg"
        },
        {
            name: "Falda urbana Denim",
            type: "pantalon",
            category_id: categoryByType.get("pantalon")!,
            price: 17900,
            description: "Falda urbana de denim para combinar con tus basicos.",
            talles: "S,M,L",
            stock: 7,
            imagen1: "falda.png"
        },
        {
            name: "Vestido Daily Black",
            type: "vestido",
            category_id: categoryByType.get("remera")!,
            price: 21900,
            description: "Vestido negro versatil para un look urbano diario.",
            talles: "S,M,L",
            stock: 6,
            imagen1: "vestido1.png"
        },
        {
            name: "Campera Urban Light",
            type: "abrigo",
            category_id: categoryByType.get("pantalon")!,
            price: 32900,
            description: "Campera liviana de inspiracion streetwear.",
            talles: "S,M,L,XL",
            stock: 5,
            imagen1: "bebestreet.png"
        }
    ];

    for (const product of products) {
        const existingProduct = await Products.findOne({ where: { name: product.name } });
        if (!existingProduct) {
            await Products.create(product);
        }
    }

    await Products.update({ sales_count: 84 }, { where: { name: "Buzo oversize Essential" } });
    await Products.update({ sales_count: 71 }, { where: { name: "Remera Street Club" } });
    await Products.update({ sales_count: 63 }, { where: { name: "Zapatillas deportivas" } });
    await Products.update({ sales_count: 55 }, { where: { name: "Pantalon de jean" } });
    await Products.update({ sales_count: 48 }, { where: { name: "Pantalon cargo Utility" } });
    await Products.update({ sales_count: 41 }, { where: { name: "Campera Urban Light" } });

    console.log(`Base lista: ${await Categories.count()} categorias, ${await Products.count()} productos.`);
}

setupDatabase()
    .catch((error) => {
        console.error("No se pudo preparar la base de datos:", error.message);
        process.exitCode = 1;
    })
    .finally(() => sequelize.close());